from pydantic import BaseModel, Field


class SNP(BaseModel):
    gene: str = Field(..., description="Gene symbol, e.g., BRCA1")
    chrom: str | None = Field(None, description="Chromosome name, e.g., 17")
    pos: int | None = Field(None, description="Genomic position")
    ref: str | None = Field(None, description="Reference allele")
    alt: str | None = Field(None, description="Alternate allele")
    type: str | None = Field(None, description="Variant type, e.g., substitution")
    explanation: str | None = Field(None, description="Explanation generated by LLM")
